@extends('layouts.fullscreen-layout')

@section('content')
<style>
/* Hallmark · macrostructure: Split Auth Desk · tone: playful-professional · anchor hue: EDUJA teal */
.auth-page{--auth-paper:#fbf6ed;--auth-ink:#173b3d;--auth-teal:#087f7a;--auth-mint:#d8f1e7;--auth-line:#d8e2da;min-height:100vh;background:var(--auth-paper);color:var(--auth-ink);overflow-x:clip}.auth-display{font-family:Georgia,'Times New Roman',serif;letter-spacing:-.055em}.auth-side{background:var(--auth-ink);position:relative;overflow:hidden}.auth-side:after{content:"";position:absolute;width:320px;height:320px;right:-110px;bottom:-120px;border:1px solid rgba(216,241,231,.22);border-radius:48% 52% 40% 60%;transform:rotate(28deg)}.auth-input{background:rgba(255,255,255,.55);border:1px solid var(--auth-line);color:var(--auth-ink);transition:border-color 160ms ease,box-shadow 160ms ease,background 160ms ease}.auth-input:hover{background:#fff;border-color:#b7cbc0}.auth-input:focus{background:#fff;border-color:var(--auth-teal);box-shadow:0 0 0 4px rgba(8,127,122,.12);outline:0}.auth-input:disabled{opacity:.55;cursor:not-allowed}.auth-button{background:var(--auth-teal);transition:transform 160ms ease,background 160ms ease,box-shadow 160ms ease}.auth-button:hover{background:#06645f;transform:translateY(-1px);box-shadow:0 10px 20px rgba(8,127,122,.18)}.auth-button:active{transform:translateY(1px)}.auth-button:focus-visible,.auth-link:focus-visible{outline:3px solid #f1c85b;outline-offset:3px}.auth-button:disabled{opacity:.55;cursor:not-allowed;transform:none;box-shadow:none}@media(max-width:767px){.auth-side{min-height:260px}.auth-content{padding-top:2rem;padding-bottom:2rem}}@media(prefers-reduced-motion:reduce){.auth-input,.auth-button{transition:none}}
</style>
<div class="auth-page grid min-h-screen md:grid-cols-[minmax(300px,0.78fr)_minmax(420px,1.22fr)]" x-data="{ role: '{{ old('registration_type', 'wali_murid') }}', copy: { wali_murid: { eyebrow: 'Untuk keluarga', title: 'Hubungkan keluarga Anda', intro: 'Buat akun untuk memilih sekolah dan mencatat data siswa yang menjadi tanggungan Anda.', side: 'Pantau kebutuhan sekolah anak dari satu tempat.', helper: 'Akun langsung aktif setelah pendaftaran.' }, guru: { eyebrow: 'Untuk pendidik', title: 'Mulai mengajar dengan rapi', intro: 'Buat akun guru untuk mengakses sekolah yang mengundang atau menerima Anda sebagai anggota.', side: 'Bawa pekerjaan mengajar ke ruang kerja yang lebih teratur.', helper: 'Verifikasi email diperlukan sebelum masuk.' }, sekolah: { eyebrow: 'Untuk sekolah', title: 'Daftarkan sekolah Anda', intro: 'Ajukan ruang kerja sekolah dan siapkan akun PIC untuk mengelola operasional bersama tim.', side: 'Bangun ruang kerja sekolah yang siap dipakai tim.', helper: 'Pendaftaran akan diperiksa superadmin sebelum aktif.' } } }">
    <aside class="auth-side flex flex-col justify-between px-7 py-8 text-white sm:px-12 md:px-14 md:py-12"><a href="/" aria-label="Kembali ke beranda"><img src="/images/logo/logo-wide-dark.png" alt="EDUJA — Sekolah Jadi Seru" class="h-10 w-auto object-contain brightness-0 invert"></a><div class="relative z-10 max-w-md py-12 md:py-0"><p class="text-sm font-bold tracking-wide text-[#f6d873]">Mulai dari kebutuhan Anda</p><h1 class="auth-display mt-5 text-5xl leading-[.96] sm:text-6xl" x-text="copy[role].title">Hubungkan keluarga Anda</h1><p class="mt-6 max-w-sm text-sm leading-7 text-white/65" x-text="copy[role].side">Pantau kebutuhan sekolah anak dari satu tempat.</p></div><p class="relative z-10 text-xs text-white/45">EDUJA · Platform operasional sekolah</p></aside>
    <main class="auth-content flex items-center justify-center px-6 py-10 sm:px-10 md:px-16"><div class="w-full max-w-[500px]">
        <a href="/" class="auth-link mb-10 inline-flex items-center gap-2 text-sm font-semibold text-[var(--auth-ink)]/55 hover:text-[var(--auth-teal)]"><i class="bx bx-arrow-back"></i> Kembali ke beranda</a>
        <div class="mb-8"><p class="text-sm font-bold text-[var(--auth-teal)]" x-text="copy[role].eyebrow">Untuk keluarga</p><h2 class="auth-display mt-2 text-5xl leading-none" x-text="copy[role].title">Hubungkan keluarga Anda</h2><p class="mt-4 text-sm leading-6 text-[var(--auth-ink)]/60" x-text="copy[role].intro">Buat akun untuk memilih sekolah dan mencatat data siswa yang menjadi tanggungan Anda.</p></div>
        @if($errors->any())<div class="mb-6 flex items-start gap-3 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700" role="alert"><i class="bx bx-error-circle mt-0.5 text-lg"></i><span>{{ $errors->first() }}</span></div>@endif
        <form action="{{ route('signup.store') }}" method="POST" class="space-y-5">@csrf
            <div><label for="registration_type" class="mb-2 block text-sm font-bold">Saya mendaftar sebagai</label><select x-model="role" @change="document.getElementById('school_code').focus()" class="auth-input w-full rounded-2xl px-4 py-3.5 text-sm" id="registration_type" name="registration_type" required><option value="wali_murid">Wali murid</option><option value="guru">Guru</option><option value="sekolah">Sekolah / PIC sekolah</option></select><p class="mt-2 text-xs leading-5 text-[var(--auth-ink)]/55" x-text="copy[role].helper">Akun langsung aktif setelah pendaftaran.</p>@error('registration_type')<p class="mt-2 text-xs font-medium text-red-700" role="alert">{{ $message }}</p>@enderror</div>
            <div class="grid grid-cols-1 gap-5 sm:grid-cols-2"><div><label for="fname" class="mb-2 block text-sm font-bold">Nama depan</label><input class="auth-input w-full rounded-2xl px-4 py-3.5 text-sm" type="text" id="fname" name="fname" value="{{ old('fname') }}" required placeholder="Nama depan" autocomplete="given-name">@error('fname')<p class="mt-2 text-xs font-medium text-red-700" role="alert">{{ $message }}</p>@enderror</div><div><label for="lname" class="mb-2 block text-sm font-bold">Nama belakang</label><input class="auth-input w-full rounded-2xl px-4 py-3.5 text-sm" type="text" id="lname" name="lname" value="{{ old('lname') }}" required placeholder="Nama belakang" autocomplete="family-name">@error('lname')<p class="mt-2 text-xs font-medium text-red-700" role="alert">{{ $message }}</p>@enderror</div></div>
            <div><label for="email" class="mb-2 block text-sm font-bold">Alamat email</label><input class="auth-input w-full rounded-2xl px-4 py-3.5 text-sm" type="email" id="email" name="email" value="{{ old('email') }}" required placeholder="nama@sekolah.sch.id" autocomplete="email">@error('email')<p class="mt-2 text-xs font-medium text-red-700" role="alert">{{ $message }}</p>@enderror</div>
            <div><label for="password" class="mb-2 block text-sm font-bold">Kata sandi</label><div x-data="{ showPassword: false }" class="relative"><input class="auth-input w-full rounded-2xl px-4 py-3.5 pr-12 text-sm" :type="showPassword ? 'text' : 'password'" id="password" name="password" required placeholder="Minimal 6 karakter" autocomplete="new-password"><button type="button" @click="showPassword = !showPassword" class="auth-link absolute right-3 top-1/2 flex h-9 w-9 -translate-y-1/2 items-center justify-center rounded-xl text-slate-400 hover:text-[var(--auth-teal)]" :aria-label="showPassword ? 'Sembunyikan kata sandi' : 'Tampilkan kata sandi'"><i x-show="!showPassword" class="bx bx-show text-lg"></i><i x-show="showPassword" class="bx bx-hide text-lg" style="display:none"></i></button></div></div>
            <div><label for="school_code" class="mb-2 block text-sm font-bold">Kode sekolah <span class="font-normal text-slate-400" x-text="role === 'guru' ? '(opsional, bisa ditambahkan setelah verifikasi email)' : '(diberikan oleh sekolah)'">(diberikan oleh sekolah)</span></label><input class="auth-input w-full rounded-2xl px-4 py-3.5 text-sm" type="text" id="school_code" name="school_code" value="{{ old('school_code') }}" placeholder="Contoh: EDUJA-ABC123"><p class="mt-2 text-xs leading-5 text-[var(--auth-ink)]/55" x-show="role === 'wali_murid'">Gunakan kode dari sekolah yang dipilih agar data siswa masuk ke sekolah yang benar.</p><p class="mt-2 text-xs leading-5 text-[var(--auth-ink)]/55" x-show="role === 'guru'" style="display:none">Guru dapat melewati kolom ini dan memilih sekolah setelah email terverifikasi.</p></div>
            <div x-show="role === 'sekolah'" style="display:none"><label for="school_name" class="mb-2 block text-sm font-bold">Nama sekolah</label><input class="auth-input w-full rounded-2xl px-4 py-3.5 text-sm" type="text" id="school_name" name="school_name" value="{{ old('school_name') }}" placeholder="Nama resmi sekolah" :required="role === 'sekolah'"><p class="mt-2 text-xs leading-5 text-[var(--auth-ink)]/55">PIC akan menjadi pengelola awal setelah sekolah disetujui.</p>@error('school_name')<p class="mt-2 text-xs font-medium text-red-700" role="alert">{{ $message }}</p>@enderror</div>
            <button type="submit" class="auth-button mt-2 w-full rounded-2xl py-4 text-sm font-bold text-white" data-submit-button><span data-submit-label>Buat akun EDUJA</span> <i class="bx bx-right-arrow-alt ml-1 align-middle text-lg" data-submit-icon></i></button>
        </form>
        <p class="mt-8 border-t border-[var(--auth-line)] pt-6 text-center text-sm text-[var(--auth-ink)]/55">Sudah memiliki akun? <a href="/signin" class="auth-link font-bold text-[var(--auth-teal)] hover:underline">Masuk sekarang</a></p>
        <button @click="$store.theme.toggle()" class="auth-link fixed bottom-6 right-6 flex h-11 w-11 items-center justify-center rounded-full border border-[var(--auth-line)] bg-white/75 text-[var(--auth-ink)] shadow-sm" aria-label="Ganti tema"><i x-show="$store.theme.theme === 'light'" class="bx bx-moon text-lg"></i><i x-show="$store.theme.theme === 'dark'" class="bx bx-sun text-lg" style="display:none"></i></button>
    </div></main>
</div>
<script>document.addEventListener('DOMContentLoaded',()=>{document.querySelector('form[action="{{ route('signup.store') }}"]')?.addEventListener('submit',e=>{const b=e.currentTarget.querySelector('[data-submit-button]');if(!b)return;b.disabled=true;b.setAttribute('aria-busy','true');b.querySelector('[data-submit-label]').textContent='Menyiapkan akun…';b.querySelector('[data-submit-icon]')?.remove();});});</script>
@endsection
