<!DOCTYPE html>
<html lang="id" class="scroll-smooth" x-data>
<head>
    @include('partials.public-head', [
        'title' => 'Eduja — Operasional Sekolah, Lebih Ringan',
        'description' => 'Eduja membantu sekolah mengelola akademik, keuangan, presensi, dan komunikasi dalam satu ruang kerja yang mudah digunakan.',
        'keywords' => 'aplikasi manajemen sekolah, sistem informasi sekolah, aplikasi sekolah Indonesia, operasional sekolah digital'
    ])
    <style>
        :root { --cream:#fbf6ed; --ink:#173b3d; --teal:#087f7a; --teal-dark:#06645f; --mint:#d8f1e7; --peach:#f5c8ad; --yellow:#f6d873; --line:#dce5dc; --shadow-card:0 18px 42px rgba(23,59,61,.10); --ease-out:cubic-bezier(.16,1,.3,1); --dur-fast:160ms; }
        body { background:var(--cream)!important; color:var(--ink); font-family: 'Inter', sans-serif; }
        .eduja-display { font-family: Georgia, 'Times New Roman', serif; letter-spacing:-.06em; }
        .landing-nav { background:rgba(251,246,237,.96); border-bottom:1px solid rgba(23,59,61,.08); }
        .paper-grid { background-image:linear-gradient(rgba(8,127,122,.045) 1px,transparent 1px),linear-gradient(90deg,rgba(8,127,122,.045) 1px,transparent 1px); background-size:26px 26px; }
        .blob { border-radius:42% 58% 62% 38% / 45% 38% 62% 55%; }
        .hero-card { box-shadow:var(--shadow-card); transform:rotate(1deg); }
        .hero-card:hover { transform:rotate(0); }
        .feature-card { border:1px solid var(--line); background:rgba(255,255,255,.52); transition:background var(--dur-fast) var(--ease-out),border-color var(--dur-fast) var(--ease-out); }
        .feature-card:hover { background:#fff; border-color:rgba(8,127,122,.28); }
        .sticker { animation:float 5s ease-in-out infinite; }
        .sticker-delay { animation-delay:-2s; }
        @keyframes float { 0%,100%{transform:translateY(0) rotate(-4deg)} 50%{transform:translateY(-9px) rotate(2deg)} }
        @media (prefers-reduced-motion:reduce){.sticker{animation:none}.hero-card,.feature-card{transition:none}}
    </style>
</head>
<body class="antialiased overflow-x-clip">
    @include('partials.public-nav', ['activePage' => 'home'])

    <main>
        <section class="paper-grid relative overflow-hidden px-6 pb-20 pt-32 md:pb-28 md:pt-44" x-data="{ activeRole: 'sekolah' }">
            <div class="mx-auto max-w-6xl">
                <div class="max-w-3xl">
                    <p class="mb-5 text-sm font-black uppercase tracking-[.2em] text-[var(--teal)]">EDUJA · Satu ruang kerja untuk sekolah</p>
                    <h1 class="eduja-display max-w-3xl text-6xl leading-[.95] text-[var(--ink)] sm:text-7xl lg:text-[86px]">Kerja sekolah lebih jelas.<br><em class="text-[var(--teal)]">Mulai dari peran Anda.</em></h1>
                    <p class="mt-7 max-w-2xl text-base leading-8 text-[var(--ink)]/65 sm:text-lg">EDUJA menghubungkan data sekolah, pekerjaan guru, dan informasi anak dalam alur yang mudah diikuti. Pilih peran Anda untuk melihat apa yang bisa langsung dikerjakan.</p>
                </div>

                <div class="mt-10 grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-stretch">
                    <div role="tablist" aria-label="Pilih peran di EDUJA" class="flex flex-col gap-3">
                        <button type="button" role="tab" :aria-selected="activeRole === 'sekolah'" @click="activeRole = 'sekolah'" class="role-tab flex min-h-[76px] items-center gap-4 rounded-2xl border border-[var(--line)] bg-white/70 p-4 text-left transition hover:border-[var(--teal)] hover:bg-white focus-visible:outline focus-visible:outline-3 focus-visible:outline-offset-2 focus-visible:outline-[var(--yellow)]" :class="activeRole === 'sekolah' ? 'border-[var(--teal)] bg-white shadow-[var(--shadow-card)]' : ''"><span class="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[var(--mint)] text-xl text-[var(--teal)]"><i class="bx bx-buildings" aria-hidden="true"></i></span><span><strong class="block text-sm font-black text-[var(--ink)]">Saya mengelola sekolah</strong><small class="mt-1 block text-xs leading-5 text-[var(--ink)]/60">Kelola data, keuangan, presensi, dan approval.</small></span></button>
                        <button type="button" role="tab" :aria-selected="activeRole === 'guru'" @click="activeRole = 'guru'" class="role-tab flex min-h-[76px] items-center gap-4 rounded-2xl border border-[var(--line)] bg-white/70 p-4 text-left transition hover:border-[var(--teal)] hover:bg-white focus-visible:outline focus-visible:outline-3 focus-visible:outline-offset-2 focus-visible:outline-[var(--yellow)]" :class="activeRole === 'guru' ? 'border-[var(--teal)] bg-white shadow-[var(--shadow-card)]' : ''"><span class="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[#fff4dc] text-xl text-[#b2760b]"><i class="bx bx-chalkboard" aria-hidden="true"></i></span><span><strong class="block text-sm font-black text-[var(--ink)]">Saya mengajar</strong><small class="mt-1 block text-xs leading-5 text-[var(--ink)]/60">Buka kelas, presensi, pengumuman, dan sekolah aktif.</small></span></button>
                        <button type="button" role="tab" :aria-selected="activeRole === 'wali'" @click="activeRole = 'wali'" class="role-tab flex min-h-[76px] items-center gap-4 rounded-2xl border border-[var(--line)] bg-white/70 p-4 text-left transition hover:border-[var(--teal)] hover:bg-white focus-visible:outline focus-visible:outline-3 focus-visible:outline-offset-2 focus-visible:outline-[var(--yellow)]" :class="activeRole === 'wali' ? 'border-[var(--teal)] bg-white shadow-[var(--shadow-card)]' : ''"><span class="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[#fff9f4] text-xl text-[#b85d37]"><i class="bx bx-group" aria-hidden="true"></i></span><span><strong class="block text-sm font-black text-[var(--ink)]">Saya wali murid</strong><small class="mt-1 block text-xs leading-5 text-[var(--ink)]/60">Pilih sekolah dan pantau informasi anak.</small></span></button>
                        <div class="mt-2 flex flex-col gap-3 sm:flex-row lg:flex-col xl:flex-row"><a href="/contact" class="inline-flex min-h-12 items-center justify-center rounded-full bg-[var(--teal)] px-6 py-3.5 text-center text-sm font-bold text-white shadow-lg shadow-[var(--teal)]/20 transition hover:bg-[var(--teal-dark)] focus-visible:outline focus-visible:outline-3 focus-visible:outline-offset-2 focus-visible:outline-[var(--yellow)]">Jadwalkan demo gratis</a><a href="/signup" class="inline-flex min-h-12 items-center justify-center rounded-full border border-[var(--ink)]/20 px-6 py-3.5 text-center text-sm font-bold text-[var(--ink)] transition hover:bg-white/70 focus-visible:outline focus-visible:outline-3 focus-visible:outline-offset-2 focus-visible:outline-[var(--yellow)]">Buat akun</a></div>
                    </div>

                    <div class="relative min-h-[330px] overflow-hidden rounded-[28px] border border-white/70 bg-[var(--ink)] p-6 text-white shadow-[var(--shadow-card)] sm:p-8">
                        <div x-show="activeRole === 'sekolah'" x-transition.opacity.duration.200ms role="tabpanel"><p class="text-xs font-black uppercase tracking-[.2em] text-[var(--yellow)]">Untuk pengelola sekolah</p><h2 class="eduja-display mt-4 max-w-md text-4xl leading-none sm:text-5xl">Tahu apa yang perlu diputuskan.</h2><p class="mt-5 max-w-md text-sm leading-7 text-white/65">Kepala sekolah dan tim melihat data yang sama saat mengelola siswa, keuangan, presensi, pengumuman, dan approval.</p><div class="mt-8 grid max-w-md grid-cols-2 gap-3"><span class="rounded-xl border border-white/10 bg-white/5 p-3 text-xs text-white/75">Dashboard sekolah</span><span class="rounded-xl border border-white/10 bg-white/5 p-3 text-xs text-white/75">Approval pengeluaran</span><span class="rounded-xl border border-white/10 bg-white/5 p-3 text-xs text-white/75">Data siswa dan GTK</span><span class="rounded-xl border border-white/10 bg-white/5 p-3 text-xs text-white/75">BOS, SPP, dan BKU</span></div></div>
                        <div x-show="activeRole === 'guru'" x-transition.opacity.duration.200ms role="tabpanel" style="display:none"><p class="text-xs font-black uppercase tracking-[.2em] text-[var(--yellow)]">Untuk guru</p><h2 class="eduja-display mt-4 max-w-md text-4xl leading-none sm:text-5xl">Buka pekerjaan yang menunggu Anda.</h2><p class="mt-5 max-w-md text-sm leading-7 text-white/65">Guru dapat berpindah sekolah, melihat konteks sekolah aktif, dan membuka informasi yang sesuai dengan perannya.</p><div class="mt-8 grid max-w-md grid-cols-2 gap-3"><span class="rounded-xl border border-white/10 bg-white/5 p-3 text-xs text-white/75">Presensi</span><span class="rounded-xl border border-white/10 bg-white/5 p-3 text-xs text-white/75">Portal guru</span><span class="rounded-xl border border-white/10 bg-white/5 p-3 text-xs text-white/75">Pengumuman</span><span class="rounded-xl border border-white/10 bg-white/5 p-3 text-xs text-white/75">Multi-sekolah</span></div></div>
                        <div x-show="activeRole === 'wali'" x-transition.opacity.duration.200ms role="tabpanel" style="display:none"><p class="text-xs font-black uppercase tracking-[.2em] text-[var(--yellow)]">Untuk wali murid</p><h2 class="eduja-display mt-4 max-w-md text-4xl leading-none sm:text-5xl">Tahu kabar sekolah anak.</h2><p class="mt-5 max-w-md text-sm leading-7 text-white/65">Wali memilih sekolah dengan kode referensi, lalu menambahkan data siswa yang terhubung ke akunnya.</p><div class="mt-8 grid max-w-md grid-cols-2 gap-3"><span class="rounded-xl border border-white/10 bg-white/5 p-3 text-xs text-white/75">Pilih sekolah</span><span class="rounded-xl border border-white/10 bg-white/5 p-3 text-xs text-white/75">Data siswa</span><span class="rounded-xl border border-white/10 bg-white/5 p-3 text-xs text-white/75">Presensi anak</span><span class="rounded-xl border border-white/10 bg-white/5 p-3 text-xs text-white/75">Informasi sekolah</span></div></div>
                    </div>
                </div>
            </div>
        </section>

        <section id="fitur" class="px-6 py-24"><div class="mx-auto max-w-6xl"><div class="max-w-2xl"><p class="text-xs font-black uppercase tracking-[.2em] text-[var(--teal)]">Yang dikerjakan EDUJA</p><h2 class="eduja-display mt-4 text-5xl leading-none sm:text-6xl">Satu ruang kerja,<br>alur yang lebih jelas.</h2></div><div class="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-4">@foreach([['icon'=>'bx-group','title'=>'Data sekolah','desc'=>'Siswa, guru, kelas, dan tahun ajaran tersusun dalam satu konteks sekolah.'],['icon'=>'bx-wallet','title'=>'Keuangan','desc'=>'Pantau SPP, BOS, BKU, approval, dan saldo dari data yang sama.'],['icon'=>'bx-calendar-check','title'=>'Presensi','desc'=>'Catat kehadiran siswa, guru, dan tendik lalu lihat rekapnya.'],['icon'=>'bx-message-rounded-dots','title'=>'Koordinasi','desc'=>'Bagikan pengumuman dan ikuti pekerjaan yang masih menunggu tindakan.']] as $feature)<article class="feature-card rounded-[20px] p-6"><div class="flex h-12 w-12 items-center justify-center rounded-2xl bg-[var(--mint)] text-2xl text-[var(--teal)]"><i class="bx {{ $feature['icon'] }}" aria-hidden="true"></i></div><h3 class="mt-6 text-base font-black">{{ $feature['title'] }}</h3><p class="mt-2 text-sm leading-6 text-[var(--ink)]/60">{{ $feature['desc'] }}</p></article>@endforeach</div></div></section>

        <section id="cara-kerja" class="bg-[var(--ink)] px-6 py-24 text-white"><div class="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p class="text-xs font-black uppercase tracking-[.2em] text-[var(--yellow)]">Mulai dengan nyaman</p><h2 class="eduja-display mt-4 text-5xl leading-none sm:text-6xl">Dari kenal,<br>jadi terbiasa.</h2><p class="mt-6 max-w-md leading-7 text-white/60">Kami menemani sekolah dari demo sampai sistem benar-benar dipakai oleh tim setiap hari.</p></div><div class="grid gap-3 sm:grid-cols-3">@foreach([['n'=>'01','t'=>'Kenali kebutuhan','d'=>'Cerita dulu tentang ritme sekolah Anda.'],['n'=>'02','t'=>'Atur bersama','d'=>'Data dan alur kerja disiapkan dengan rapi.'],['n'=>'03','t'=>'Jalankan harian','d'=>'Tim siap bekerja lebih ringan bersama Eduja.']] as $step)<div class="rounded-[24px] border border-white/10 bg-white/5 p-5"><span class="text-3xl font-black text-[var(--yellow)]">{{ $step['n'] }}</span><h3 class="mt-10 font-black">{{ $step['t'] }}</h3><p class="mt-2 text-sm leading-6 text-white/55">{{ $step['d'] }}</p></div>@endforeach</div></div></section>

        <section class="px-6 py-24"><div class="mx-auto flex max-w-4xl flex-col items-center rounded-[36px] bg-[var(--mint)] px-7 py-14 text-center"><h2 class="eduja-display mt-4 text-5xl leading-none sm:text-6xl">Saat sistemnya jelas,<br>sekolah bisa melangkah lebih jauh.</h2><p class="mt-5 max-w-lg text-sm leading-7 text-[var(--ink)]/65">Temukan bagaimana EDUJA membantu tim sekolah bekerja lebih efektif, transparan, dan fokus pada pendidikan.</p><a href="/contact" class="mt-8 rounded-full bg-[var(--teal)] px-7 py-3.5 text-sm font-bold text-white transition hover:bg-[#06645f]">Jadwalkan konsultasi <i class="bx bx-right-arrow-alt ml-1"></i></a></div></section>
    </main>
    @include('partials.public-footer')
    @include('partials.public-scripts')
</body>
</html>
